-- SELECT * FROM USERS;

-- SELECT * FROM POLYGONS WHERE POLYGON_NAME = 'Polygon A';
-- SELECT * 
-- FROM POLYGON_PARAMETER_DEFAULT 
-- WHERE POLYGON_ID = (SELECT POLYGON_ID FROM POLYGONS WHERE POLYGON_NAME = 'Polygon A')
-- AND PARAMETER_ID = (SELECT PARAMETER_ID FROM PARAMETERS WHERE PARAMETER_NAME = 'H1');

-- DELETE FROM ACCESS_KEYS WHERE USER_ID = 'c80e5b6e-8e5d-4ee9-a166-59ca0aafac5b';

-- DELETE FROM USERS WHERE EMAIL = 'Leo Das';

SELECT * FROM ACCESS_KEYS;